# Input nucleotide FASTA file generated by Prokka
ffn_file="${prokaa_dir}/${sample}/${sample}.ffn"

# Output files
out_m8="${sample}_alnRes.m8"
filtered_m8="${sample}_alnRes.filtered.m8"
module_count="${sample}_alnRes.filtered.module_count"

###############################################################################
# Step 1. Search predicted genes against the target database using MMseqs2
#
# --search-type 3 : nucleotide-to-protein translated search
# --format-output : customized BLAST-like tabular output containing:
#   query      = query sequence ID
#   target     = matched database sequence ID
#   fident     = percentage identity
#   alnlen     = alignment length
#   mismatch   = number of mismatches
#   gapopen    = number of gap openings
#   qstart/qend= query alignment coordinates
#   tstart/tend= target alignment coordinates
#   evalue     = E-value
#   bits       = bit score
#   qcov       = query coverage
#   tcov       = target coverage
###############################################################################
mmseqs easy-search \
  "$ffn_file" \
  targetDB \
  "$out_m8" \
  tmp \
  --search-type 3 \
  --format-output "query,target,fident,alnlen,mismatch,gapopen,qstart,qend,tstart,tend,evalue,bits,qcov,tcov"

###############################################################################
# Step 2. Filter MMseqs2 alignments and summarize module hit
#
# Input:
#   - Raw MMseqs2 alignment results (.m8)
#   - Enriched module file
#
# Output:
#   - Filtered alignments
#   - Per-module hit counts
###############################################################################
Rscript process_aligns.R \
  "$out_m8" \
  "$enriched_modules" \
  "$filtered_m8" \
  "$module_count"
  
###############################################################################
# Step 3. Retain only sufficiently covered modules
#
# A module is retained only if more than 50% of its constituent genes are mapped by the identified hits.
#
###############################################################################
Rscript filter_m8_by_modules.R 